
import conexion.ConexionMySQL;
import javax.swing.table.DefaultTableModel;
import conexion.Validaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FrameModificar extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    public Validaciones v1=new Validaciones();

    /**
     * Creates new form FrameModificar
     */
    public FrameModificar() {
        initComponents();
        jComboBox1.addItem("Masculino");
        jComboBox1.addItem("Femenino");
        inhabilitar();
    }
     private void inhabilitar()
    {
        jTextField_Rut.setEnabled(false);
        jTextField_Nombre1.setEnabled(false);
        jTextField_Nombre2.setEnabled(false);
        jTextField_Apellido1.setEnabled(false);
        jTextField_Apellido2.setEnabled(false);
        jTextField_Fecha.setEnabled(false);
        jComboBox1.setEnabled(false);
    }
     private void habilitar()
     {
         jTextField_Rut.setEnabled(true);
        jTextField_Nombre1.setEnabled(true);
        jTextField_Nombre2.setEnabled(true);
        jTextField_Apellido1.setEnabled(true);
        jTextField_Apellido2.setEnabled(true);
        jTextField_Fecha.setEnabled(true);
        jComboBox1.setEnabled(true);
     }
     private void BuscarAlumnoEditar(String id)
     {
       
        
         String nom="", nom1="", ape="", ape1="", fech="", gen="" ;
         // Conectar con la base de datos 
         ConexionMySQL mysql= new ConexionMySQL();
         java.sql.Connection cn= mysql.Conectar();
         // La consulta de selección de datos
         String sSQL="SELECT idalumno, nombre1, nombre2, apellido1, apellido2, fecha, genero FROM alumnos" +
                       "WHERE idalumno="+id; 
          // Ejecute la consulta
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            // Llene la tabla con los datos de registro y pasar estos datos a un elemento jTable1 del formulario 
            while (rs.next())
            {
                
                nom=rs.getString("nombre1");
                nom1=rs.getString("nombre2");
                ape=rs.getString("apellido1");
                ape1=rs.getString("apellido2");
                fech=rs.getString("fecha");
                gen=rs.getString("genero");
                
            }
                jTextField_Nombre1.setText(nom);
                jTextField_Nombre2.setText(nom1);
                jTextField_Apellido1.setText(ape);
                jTextField_Apellido2.setText(ape1);
                jTextField_Fecha.setText(fech);
                jComboBox1.setSelectedItem(gen);
            // En caso de error puede llenar el mensaje de error
            } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Mensaje de Error de lectura de datos"); 
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldModificar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModificar = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField_Fecha = new javax.swing.JTextField();
        jTextField_Apellido2 = new javax.swing.JTextField();
        jTextField_Apellido1 = new javax.swing.JTextField();
        jTextField_Nombre2 = new javax.swing.JTextField();
        jTextField_Nombre1 = new javax.swing.JTextField();
        jTextField_Rut = new javax.swing.JTextField();
        jButtonDatosAlumno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItemEditar.setText("Modificar");
        jMenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 102)));

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Ingrese Rut a Modificar:");

        jTextFieldModificar.setBackground(new java.awt.Color(204, 255, 255));

        jTableModificar.setBackground(new java.awt.Color(204, 255, 255));
        jTableModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdAlumno", "Nombre1", "Nombre2", "Apellido1", "Apellido2", "Fecha ", "Genero"
            }
        ));
        jTableModificar.setComponentPopupMenu(jPopupMenu1);
        jTableModificar.setMinimumSize(new java.awt.Dimension(520, 16));
        jScrollPane1.setViewportView(jTableModificar);

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Fecha Nacimiento:");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Genero");

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Primer apellido:");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Segundo apellido:");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Rut:");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Segundo nombre:");

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Primer nombre:");

        jComboBox1.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(204, 255, 255));

        jTextField_Fecha.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Fecha.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Fecha.setText("ejemplo 1988-02-25");
        jTextField_Fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FechaKeyTyped(evt);
            }
        });

        jTextField_Apellido2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Apellido2.setForeground(new java.awt.Color(0, 102, 102));

        jTextField_Apellido1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Apellido1.setForeground(new java.awt.Color(0, 102, 102));

        jTextField_Nombre2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nombre2.setForeground(new java.awt.Color(0, 102, 102));

        jTextField_Nombre1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nombre1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nombre1ActionPerformed(evt);
            }
        });

        jTextField_Rut.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Rut.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RutActionPerformed(evt);
            }
        });

        jButtonDatosAlumno.setForeground(new java.awt.Color(0, 102, 102));
        jButtonDatosAlumno.setText("Motrar datos alumno");
        jButtonDatosAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosAlumnoActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90)
                                        .addComponent(jTextFieldModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)))
                                                .addGap(85, 85, 85)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jTextField_Apellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_Nombre2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_Nombre1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_Apellido2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                    .addComponent(jTextField_Rut))))))
                                .addGap(0, 59, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jButtonDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addComponent(jButtonDatosAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(520, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FechaKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_FechaKeyTyped

    private void jTextField_Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nombre1ActionPerformed

    private void jTextField_RutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RutActionPerformed

    }//GEN-LAST:event_jTextField_RutActionPerformed

    private void jButtonDatosAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosAlumnoActionPerformed
        // TODO add your handling code here:
         String Busca= jTextFieldModificar.getText();
          // Validar los datos que no sean blancos
        if ("".equals(Busca))
            {
            
                JOptionPane.showMessageDialog(null, "Debe ingresar Rut");
                return;
            }
        
        else
        {
            if (v1.solonumeros(Busca)== false)
            {
            JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo Rut");
            return;
            }
        // un registro para recuperar los datos desde la consulta SQL
         String[] registro = new String[7];
         String[] Titulos={"Idalumno" , "Nombre1", "Nombre2", "Apellido1","Apellido2", "Fecha", "Genero"};
        // Un modelo contenedor para los datos que sean leidos  
        modelo = new DefaultTableModel(null,Titulos);
        // Conectar con la base de datos 
        ConexionMySQL mysql= new ConexionMySQL();
        java.sql.Connection cn= mysql.Conectar();
        // La consulta de selección de datos
        String sSQL="SELECT idalumno, nombre1, nombre2, apellido1, apellido2, fecha, genero FROM alumnos WHERE idalumno LIKE '%"+Busca+"%'";
        // Ejecute la consulta
        try {
            java.sql.Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            // Llene la tabla con los datos de registro y pasar estos datos a un elemento jTable1 del formulario 
            while (rs.next())
            {
                registro[0]=rs.getString("idalumno");
                registro[1]=rs.getString("nombre1");
                registro[2]=rs.getString("nombre2");
                registro[3]=rs.getString("apellido1");
                registro[4]=rs.getString("apellido2");
                registro[5]=rs.getString("fecha");
                registro[6]=rs.getString("genero");
                modelo.addRow(registro);
            }
            jTableModificar.setModel(modelo);
            
            
            // En caso de error puede llenar el mensaje de error
            } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Mensaje de Error de lectura de datos"); 
            }
        }
    }//GEN-LAST:event_jButtonDatosAlumnoActionPerformed

    private void jMenuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarActionPerformed
        // TODO add your handling code here:
        int  filasel;
        String id;
        
        try 
        {
            filasel = jTableModificar.getSelectedRow();
            if(filasel == -1)
            {
                JOptionPane.showMessageDialog(null, "no se a seleccionado ninguna fila");
            }
            else
            {
                //accion ="Modificar";
                habilitar();
                modelo = (DefaultTableModel)jTableModificar.getModel();
                id = (String) modelo.getValueAt(filasel, 0 );
                BuscarAlumnoEditar(id);
            }
        }
        catch (Exception e) 
        {
            inhabilitar();
        }
    }//GEN-LAST:event_jMenuItemEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrameModificar.this.setVisible(false);
        new Mantenedor().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameModificar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDatosAlumno;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModificar;
    private javax.swing.JTextField jTextFieldModificar;
    private javax.swing.JTextField jTextField_Apellido1;
    private javax.swing.JTextField jTextField_Apellido2;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_Nombre1;
    private javax.swing.JTextField jTextField_Nombre2;
    private javax.swing.JTextField jTextField_Rut;
    // End of variables declaration//GEN-END:variables
}
