/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import conexion.ConexionMySQL;
import conexion.Validaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILLE
 */
public class FrameConsultar extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    public Validaciones v1=new Validaciones();
    /**
     * Creates new form FrameConsultar
     */
    public FrameConsultar() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_Consultar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_Consultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_VolverConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 102)));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        jTextField_Consultar.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Consultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ConsultarKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Ingrese rut a consultar:");

        jButton_Consultar.setForeground(new java.awt.Color(0, 102, 102));
        jButton_Consultar.setText("Consultar");
        jButton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre1", "Nombre2", "Apellido1", "Apellido2", "Fecha", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.setGridColor(new java.awt.Color(0, 102, 102));
        jTable2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(jTable2);

        jButton_VolverConsulta.setForeground(new java.awt.Color(0, 102, 102));
        jButton_VolverConsulta.setText("Volver");
        jButton_VolverConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jTextField_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton_VolverConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton_Consultar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_VolverConsulta)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(520, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarActionPerformed
        // TODO add your handling code here:
        String Busca= jTextField_Consultar.getText();
        String id;
          // Validar los datos que no sean blancos
        if ("".equals(Busca))
            {
            
                JOptionPane.showMessageDialog(null, "Debe ingresar Rut");
                return;
            }
        
        else
        {
            if (v1.solonumeros(Busca)== false)
            {
            JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo Rut");
            return;
            }
        // un registro para recuperar los datos desde la consulta SQL
         String[] registro = new String[7];
         String[] Titulos={"Idalumno" , "Nombre1", "Nombre2", "Apellido1","Apellido2", "Fecha", "Genero"};
        // Un modelo contenedor para los datos que sean leidos  
        modelo = new DefaultTableModel(null,Titulos);
        // Conectar con la base de datos 
        ConexionMySQL mysql= new ConexionMySQL();
        java.sql.Connection cn= mysql.Conectar();
        // La consulta de selección de datos
        String sSQL="SELECT idalumno, nombre1, nombre2, apellido1, apellido2, fecha, genero FROM alumnos WHERE idalumno LIKE '%"+Busca+"%'";
        // Ejecute la consulta
        try {
            java.sql.Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sSQL);
            // Llene la tabla con los datos de registro y pasar estos datos a un elemento jTable1 del formulario 
            while (rs.next())
            {
                registro[0]=rs.getString("idalumno");
                registro[1]=rs.getString("nombre1");
                registro[2]=rs.getString("nombre2");
                registro[3]=rs.getString("apellido1");
                registro[4]=rs.getString("apellido2");
                registro[5]=rs.getString("fecha");
                registro[6]=rs.getString("genero");
                modelo.addRow(registro);
            }
            jTable2.setModel(modelo);
            modelo = (DefaultTableModel)jTable2.getModel();
            id = (String) modelo.getValueAt(1, 0);
            if(id!= Busca) 
            {
              JOptionPane.showMessageDialog(null, "Alumno encontrado"); 
            }
            
            // En caso de error puede llenar el mensaje de error
            } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Mensaje de Error de lectura de datos"); 
            }
        }
    }//GEN-LAST:event_jButton_ConsultarActionPerformed

    private void jButton_VolverConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverConsultaActionPerformed
        // TODO add your handling code here:
        FrameConsultar.this.setVisible(false);
        new Mantenedor().setVisible(true);
    }//GEN-LAST:event_jButton_VolverConsultaActionPerformed

    private void jTextField_ConsultarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ConsultarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_jTextField_ConsultarKeyTyped
    
            public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameConsultar().setVisible(true);
            }
        });
    }
        
    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Consultar;
    private javax.swing.JButton jButton_VolverConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_Consultar;
    // End of variables declaration//GEN-END:variables
}
