
import conexion.ConexionMySQL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import conexion.Validaciones;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author GUILLE
 */
public class FrameIngresar extends javax.swing.JFrame {
public Validaciones v1=new Validaciones();
    /**
     * Creates new form FrameIngresar
     */
    public FrameIngresar() {
        initComponents();
        jComboBox1.addItem("Masculino");
        jComboBox1.addItem("Femenino");
    }
    void limpiar()
    {
        jTextField_Rut.setText("");
        jTextField_Nombre1.setText("");
        jTextField_Nombre2.setText("");
        jTextField_Apellido1.setText("");
        jTextField_Apellido2.setText("");
        jTextField_Fecha.setText("ejemplo 1988-02-25");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Ingresar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_Volver = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField_Fecha = new javax.swing.JTextField();
        jTextField_Apellido2 = new javax.swing.JTextField();
        jTextField_Apellido1 = new javax.swing.JTextField();
        jTextField_Nombre2 = new javax.swing.JTextField();
        jTextField_Nombre1 = new javax.swing.JTextField();
        jTextField_Rut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario ingreso alumnos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 102, 102)));

        jButton_Ingresar.setForeground(new java.awt.Color(0, 102, 102));
        jButton_Ingresar.setText("Ingresar");
        jButton_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setForeground(new java.awt.Color(0, 102, 102));
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_Volver.setForeground(new java.awt.Color(0, 102, 102));
        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jComboBox1.setForeground(new java.awt.Color(0, 102, 102));

        jTextField_Fecha.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Fecha.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Fecha.setText("ejemplo 1988-02-25");
        jTextField_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FechaActionPerformed(evt);
            }
        });
        jTextField_Fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FechaKeyTyped(evt);
            }
        });

        jTextField_Apellido2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Apellido2.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Apellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Apellido2KeyTyped(evt);
            }
        });

        jTextField_Apellido1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Apellido1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Apellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Apellido1KeyTyped(evt);
            }
        });

        jTextField_Nombre2.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nombre2.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Nombre2KeyTyped(evt);
            }
        });

        jTextField_Nombre1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Nombre1.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nombre1ActionPerformed(evt);
            }
        });
        jTextField_Nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Nombre1KeyTyped(evt);
            }
        });

        jTextField_Rut.setBackground(new java.awt.Color(204, 255, 255));
        jTextField_Rut.setForeground(new java.awt.Color(0, 102, 102));
        jTextField_Rut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RutActionPerformed(evt);
            }
        });
        jTextField_Rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_RutKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Rut:");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Primer nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Segundo nombre:");

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Primer apellido:");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Segundo apellido:");

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Fecha Nacimiento:");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Genero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jButton_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jButton_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Nombre2)
                            .addComponent(jTextField_Nombre1)
                            .addComponent(jTextField_Rut)
                            .addComponent(jTextField_Apellido1)
                            .addComponent(jTextField_Apellido2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Ingresar)
                    .addComponent(jButton_Cancelar)
                    .addComponent(jButton_Volver))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(520, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresarActionPerformed
         // mensajes
        String Mensaje="Registro realizado correctamente";
        String MensajeError="Error al ingresar los datos";
        String sSQL; 
        
        //lectura de los datos del formulario
        String idalumno   = jTextField_Rut.getText(); 
        String nombre1    = jTextField_Nombre1.getText();
        String nombre2    = jTextField_Nombre2.getText();
        String apellido1  = jTextField_Apellido1.getText();
        String apellido2  = jTextField_Apellido2.getText();
        String fecha       = jTextField_Fecha.getText();
        String genero     = jComboBox1.getSelectedItem().toString();
         // Validar los datos que no sean blancos
        if ("".equals(idalumno))
            {
            
                JOptionPane.showMessageDialog(null, "Debe ingresar Rut");
                return;
            }
        
        else
        {
            if (v1.solonumeros(idalumno)== false)
            {
            JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo Rut");
            return;
            }
        }
        if ("".equals(nombre1))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar su primer Nombre");
            return;
        }
        if ("".equals(nombre2))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar su segundo Nombre");
            return;
        }
        if ("".equals(apellido1))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar su primer Apellido");
            return;
        }
        if ("".equals(apellido2))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar su segundo Apellido");
            return;
        }
        
        if ("".equals(fecha)) 
        {
            
            JOptionPane.showMessageDialog(null, "Debe ingresar Fecha");
            return;
        }
        
           
        
        //  antes de colocar las validciones funionaba *
        // Abra una conexión
        ConexionMySQL mysql= new ConexionMySQL();
        java.sql.Connection cn= mysql.Conectar();

        // Escriba la consulta SQL, los signos ? Son los parámetros que representan los campos de la tabla pelicula
           
        sSQL="INSERT INTO alumnos (idalumno, nombre1, nombre2, apellido1, apellido2, fecha, genero)"
                + "VALUES (?,?,?,?,?,?,?)";
        // ejecuta la consulta llenando los parámetros con los valores capturados e inserta los datos en la base de datos
        try
        {
            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.setString(1,idalumno);
            pst.setString(2,nombre1);
            pst.setString(3,nombre2);
            pst.setString(4,apellido1);
            pst.setString(5,apellido2);
            pst.setString(6,fecha);
            pst.setString(7, genero);
          //pst.setString(6,idcurso_FK);
            int n = pst.executeUpdate();
            JOptionPane.showMessageDialog(null, Mensaje);
            limpiar();
            jTextField_Rut.requestFocus();
            //cargarDatos();
            
        } 
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, MensajeError);
        }
        
    }//GEN-LAST:event_jButton_IngresarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        FrameIngresar.this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jTextField_RutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RutActionPerformed
        
    }//GEN-LAST:event_jTextField_RutActionPerformed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        // TODO add your handling code here:
        FrameIngresar.this.setVisible(false);
        new Mantenedor().setVisible(true);
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jTextField_FechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FechaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
        
    }//GEN-LAST:event_jTextField_FechaKeyTyped

    private void jTextField_Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nombre1ActionPerformed

    private void jTextField_RutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_RutKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
        
    }//GEN-LAST:event_jTextField_RutKeyTyped

    private void jTextField_Nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Nombre1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'a' || c>'z')evt.consume();
    }//GEN-LAST:event_jTextField_Nombre1KeyTyped

    private void jTextField_Nombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Nombre2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'a' || c>'z')evt.consume();
    }//GEN-LAST:event_jTextField_Nombre2KeyTyped

    private void jTextField_Apellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Apellido1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'a' || c>'z')evt.consume();
    }//GEN-LAST:event_jTextField_Apellido1KeyTyped

    private void jTextField_Apellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Apellido2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'a' || c>'z')evt.consume();
    }//GEN-LAST:event_jTextField_Apellido2KeyTyped

    private void jTextField_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIngresar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Ingresar;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Apellido1;
    private javax.swing.JTextField jTextField_Apellido2;
    private javax.swing.JTextField jTextField_Fecha;
    private javax.swing.JTextField jTextField_Nombre1;
    private javax.swing.JTextField jTextField_Nombre2;
    private javax.swing.JTextField jTextField_Rut;
    // End of variables declaration//GEN-END:variables
}
