
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GUILLE
 */
public class Mantenedor extends javax.swing.JFrame {

    /**
     * Creates new form Mantenedor
     */
    public Mantenedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Ingresar = new javax.swing.JMenuItem();
        jMenuItem_Consultar = new javax.swing.JMenuItem();
        jMenuItem_Eliminar = new javax.swing.JMenuItem();
        jMenuItem_Modificar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Listar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor");
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper-negro-2269.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, "card2");

        jMenu1.setBackground(new java.awt.Color(153, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 102, 102));
        jMenu1.setText("Mantenedor");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem_Ingresar.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Ingresar.setText("Ingresar");
        jMenuItem_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_IngresarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Ingresar);

        jMenuItem_Consultar.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Consultar.setText("Consultar");
        jMenuItem_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Consultar);

        jMenuItem_Eliminar.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Eliminar.setText("Eliminar");
        jMenuItem_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EliminarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Eliminar);

        jMenuItem_Modificar.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Modificar.setText("Modificar");
        jMenuItem_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ModificarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Modificar);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 102));
        jMenu2.setText("Procesos");

        jMenuItem_Listar.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Listar.setText("Listar curso");
        jMenuItem_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ListarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Listar);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 102, 102));
        jMenu3.setText("Salir");

        jMenuItem_Salir.setForeground(new java.awt.Color(0, 102, 102));
        jMenuItem_Salir.setText("Salir");
        jMenuItem_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SalirActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Salir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(520, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_IngresarActionPerformed
        // TODO add your handling code here:
        new FrameIngresar().setVisible(true);
        Mantenedor.this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_IngresarActionPerformed

    private void jMenuItem_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem_SalirActionPerformed

    private void jMenuItem_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarActionPerformed
        // TODO add your handling code here:
        new FrameConsultar().setVisible(true);
        Mantenedor.this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_ConsultarActionPerformed

    private void jMenuItem_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EliminarActionPerformed
        // TODO add your handling code here:
        new FrameEliminar().setVisible(true);
        Mantenedor.this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem_EliminarActionPerformed

    private void jMenuItem_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ListarActionPerformed
        // TODO add your handling code here:
        new FrameListar().setVisible(true);
        Mantenedor.this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem_ListarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ModificarActionPerformed
        // TODO add your handling code here:
       new FrameModificar().setVisible(true);
       Mantenedor.this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Consultar;
    private javax.swing.JMenuItem jMenuItem_Eliminar;
    private javax.swing.JMenuItem jMenuItem_Ingresar;
    private javax.swing.JMenuItem jMenuItem_Listar;
    private javax.swing.JMenuItem jMenuItem_Modificar;
    private javax.swing.JMenuItem jMenuItem_Salir;
    // End of variables declaration//GEN-END:variables
}
